export const DASHBOARD_STATS = [
  { label: 'Registered Drivers', value: '3', trend: '+1', icon: 'Users' },
  { label: 'Drowsy Today', value: '1', trend: '-50%', icon: 'UserX', color: 'text-brand-red' },
  { label: 'Alerts Today', value: '5', trend: '+2', icon: 'AlertTriangle' },
  { label: 'Active Sessions', value: '1', trend: '—', icon: 'Cpu' },
];

export const DROWSINESS_INCIDENTS = [
  { day: 'Mon', incidents: 4 },
  { day: 'Tue', incidents: 7 },
  { day: 'Wed', incidents: 3 },
  { day: 'Thu', incidents: 5 },
  { day: 'Fri', incidents: 8 },
  { day: 'Sat', incidents: 2 },
  { day: 'Sun', incidents: 1 },
];

export const PEAK_HOURS = [
  { hour: '00:00', incidents: 2 },
  { hour: '04:00', incidents: 5 },
  { hour: '08:00', incidents: 1 },
  { hour: '12:00', incidents: 0 },
  { hour: '16:00', incidents: 3 },
  { hour: '20:00', incidents: 6 },
];

export const MOCK_DRIVERS = [
  {
    id: 'DRV001',
    name: 'Driver 1',
    busId: 'BUS-001',
    status: 'Normal',
    lastAlert: '2h ago',
    riskLevel: 'Low',
    avatar: '/images/avatar-1.jpg',
    faceRegistered: true,
    faceRegisteredAt: '2025-10-12 08:30',
    totalSessions: 148,
    todayWorkHours: 3.2,
    todaySessions: 2,
    detectionStatus: 'monitoring',
    baselineStatus: 'learned',
    baselineConfidence: 92,
  },
  {
    id: 'DRV002',
    name: 'Driver 2',
    busId: 'BUS-001',
    status: 'Drowsy',
    lastAlert: '5m ago',
    riskLevel: 'High',
    avatar: '/images/avatar-2.jpg',
    faceRegistered: true,
    faceRegisteredAt: '2025-11-03 09:15',
    totalSessions: 96,
    todayWorkHours: 5.8,
    todaySessions: 3,
    detectionStatus: 'drowsy_detected',
    baselineStatus: 'deviation',
    baselineConfidence: 78,
  },
  {
    id: 'DRV003',
    name: 'Driver 3',
    busId: 'BUS-001',
    status: 'Stationary',
    lastAlert: 'N/A',
    riskLevel: 'Low',
    avatar: '/images/avatar-3.jpg',
    faceRegistered: true,
    faceRegisteredAt: '2025-09-22 07:45',
    totalSessions: 210,
    todayWorkHours: 1.5,
    todaySessions: 1,
    detectionStatus: 'idle',
    baselineStatus: 'learning',
    baselineConfidence: 45,
  },
];

// Active detection status for real-time monitoring feed
export const DETECTION_FEED = [
  { id: 'DET001', driverId: 'DRV002', driver: 'Driver 2', type: 'drowsy_detected', confidence: 87, timestamp: '14:32:05', alarmTriggered: true, alarmType: 'buzzer_oled', vehicleMoving: true, baselineDeviation: 34 },
  { id: 'DET002', driverId: 'DRV001', driver: 'Driver 1', type: 'baseline_deviation', confidence: 72, timestamp: '14:28:41', alarmTriggered: false, alarmType: 'visual_only', vehicleMoving: true, baselineDeviation: 22 },
  { id: 'DET003', driverId: 'DRV002', driver: 'Driver 2', type: 'continuous_drowsy', confidence: 91, timestamp: '14:25:12', alarmTriggered: true, alarmType: 'buzzer_oled', vehicleMoving: true, baselineDeviation: 42 },
  { id: 'DET004', driverId: 'DRV001', driver: 'Driver 1', type: 'normal', confidence: 95, timestamp: '14:20:00', alarmTriggered: false, alarmType: 'none', vehicleMoving: true, baselineDeviation: 5 },
  { id: 'DET005', driverId: 'DRV003', driver: 'Driver 3', type: 'normal', confidence: 88, timestamp: '14:15:33', alarmTriggered: false, alarmType: 'none', vehicleMoving: false, baselineDeviation: 8 },
];

// Driver sessions data
export const DRIVER_SESSIONS = [
  {
    id: 'SES-20260312-001',
    driverId: 'DRV001',
    driver: 'Driver 1',
    busId: 'BUS-001',
    startTime: '2026-03-12 06:14',
    endTime: null,
    duration: '3h 12m',
    status: 'active',
    alertCount: 1,
    baselineStatus: 'learned',
    baselineConfidence: 92,
    drowsinessEvents: 1,
  },
  {
    id: 'SES-20260312-002',
    driverId: 'DRV002',
    driver: 'Driver 2',
    busId: 'BUS-001',
    startTime: '2026-03-12 04:30',
    endTime: null,
    duration: '5h 48m',
    status: 'active',
    alertCount: 5,
    baselineStatus: 'deviation',
    baselineConfidence: 78,
    drowsinessEvents: 4,
  },
  {
    id: 'SES-20260312-003',
    driverId: 'DRV003',
    driver: 'Driver 3',
    busId: 'BUS-001',
    startTime: '2026-03-12 08:45',
    endTime: null,
    duration: '1h 30m',
    status: 'active',
    alertCount: 0,
    baselineStatus: 'learning',
    baselineConfidence: 45,
    drowsinessEvents: 0,
  },
  {
    id: 'SES-20260311-004',
    driverId: 'DRV001',
    driver: 'Driver 1',
    busId: 'BUS-001',
    startTime: '2026-03-11 14:00',
    endTime: '2026-03-11 18:30',
    duration: '4h 30m',
    status: 'completed',
    alertCount: 2,
    baselineStatus: 'learned',
    baselineConfidence: 94,
    drowsinessEvents: 2,
  },
  {
    id: 'SES-20260311-005',
    driverId: 'DRV002',
    driver: 'Driver 2',
    busId: 'BUS-001',
    startTime: '2026-03-11 06:00',
    endTime: '2026-03-11 10:15',
    duration: '4h 15m',
    status: 'completed',
    alertCount: 3,
    baselineStatus: 'learned',
    baselineConfidence: 85,
    drowsinessEvents: 3,
  },
];

// Work hours tracking per driver
export const WORK_HOURS_DATA = [
  {
    driverId: 'DRV001',
    driver: 'Driver 1',
    todayTotal: 3.2,
    sessions: [
      { start: '06:14', end: null, duration: 3.2, active: true },
    ],
    threshold4h: false,
    threshold8h: false,
    reminderActive: false,
    weeklyHours: [6.5, 7.2, 5.8, 8.1, 6.0, 3.2, 0],
  },
  {
    driverId: 'DRV002',
    driver: 'Driver 2',
    todayTotal: 5.8,
    sessions: [
      { start: '04:30', end: '07:00', duration: 2.5, active: false },
      { start: '08:15', end: '09:30', duration: 1.25, active: false },
      { start: '10:00', end: null, duration: 2.05, active: true },
    ],
    threshold4h: true,
    threshold8h: false,
    reminderActive: true,
    weeklyHours: [7.8, 8.2, 6.5, 7.0, 8.5, 5.8, 0],
  },
  {
    driverId: 'DRV003',
    driver: 'Driver 3',
    todayTotal: 1.5,
    sessions: [
      { start: '08:45', end: null, duration: 1.5, active: true },
    ],
    threshold4h: false,
    threshold8h: false,
    reminderActive: false,
    weeklyHours: [5.0, 6.2, 4.8, 7.5, 5.5, 1.5, 0],
  },
];

export const MOCK_ALERTS = [
  {
    id: 'ALT001',
    type: 'Drowsiness Detected',
    driver: 'Driver 2',
    bus: 'BUS-001',
    timestamp: '2026-03-12 14:30',
    location: 'Highway 10, Sector 4',
    status: 'Acknowledged',
    severity: 'High',
    sessionId: 'SES-20260312-002',
    alarmType: 'buzzer_oled',
    baselineDeviation: 34,
  },
  {
    id: 'ALT002',
    type: 'Baseline Deviation',
    driver: 'Driver 1',
    bus: 'BUS-001',
    timestamp: '2026-03-12 13:15',
    location: 'Route 8A, KM 12',
    status: 'Resolved',
    severity: 'Medium',
    sessionId: 'SES-20260312-001',
    alarmType: 'visual_only',
    baselineDeviation: 22,
  },
  {
    id: 'ALT003',
    type: 'Continuous Drowsiness',
    driver: 'Driver 2',
    bus: 'BUS-001',
    timestamp: '2026-03-12 12:45',
    location: 'EDSA, Quezon Avenue',
    status: 'Active',
    severity: 'High',
    sessionId: 'SES-20260312-002',
    alarmType: 'buzzer_oled',
    baselineDeviation: 42,
  },
  {
    id: 'ALT004',
    type: 'Work Hour Threshold',
    driver: 'Driver 2',
    bus: 'BUS-001',
    timestamp: '2026-03-12 08:30',
    location: 'Taft Avenue, Manila',
    status: 'Active',
    severity: 'Medium',
    sessionId: 'SES-20260312-002',
    alarmType: 'visual_only',
    baselineDeviation: 0,
  },
  {
    id: 'ALT005',
    type: 'New Face Detected',
    driver: 'Unknown (Auto-Registered)',
    bus: 'BUS-001',
    timestamp: '2026-03-12 07:00',
    location: 'Pasay Terminal',
    status: 'Resolved',
    severity: 'Low',
    sessionId: 'SES-20260312-006',
    alarmType: 'none',
    baselineDeviation: 0,
  },
];

export const BUSES = [
  { id: 'BUS-001', driver: 'Driver 1', status: 'Online', battery: '85%', speed: '65 km/h', location: [14.5995, 120.9842] as [number, number], driverId: 'DRV001', detectionStatus: 'monitoring', sessionId: 'SES-20260312-001' },
];

export const RECENT_ALERTS = [
  { id: 'ALT001', type: 'Drowsiness Detected', driver: 'Driver 2', time: '5m ago', status: 'Active', sessionId: 'SES-20260312-002', alarmTriggered: true },
  { id: 'ALT002', type: 'Baseline Deviation', driver: 'Driver 1', time: '12m ago', status: 'Acknowledged', sessionId: 'SES-20260312-001', alarmTriggered: false },
  { id: 'ALT003', type: 'Continuous Drowsiness', driver: 'Driver 2', time: '25m ago', status: 'Active', sessionId: 'SES-20260312-002', alarmTriggered: true },
  { id: 'ALT004', type: 'Work Hour Warning (4h)', driver: 'Driver 2', time: '38m ago', status: 'Resolved', sessionId: 'SES-20260312-002', alarmTriggered: false },
];
